# PATH extension for mkdocs will not work properly without sudo
sudo: required
language: python

# Output python and pip versions for local debugging
before_install:
  - python -V
  - pip -V

# Install mkdocs and material before building
install:
  - pip install mkdocs
  - pip install mkdocs-material

# Output mkdocs and mkdocs-material versions for local debugging
after_install:
  -  pip show mkdocs
  -  pip show mkdocs-material

# Build and Deploy
script:
  - mkdocs build --verbose --clean

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: site
 on:
   branch: master

# Only build on master; changes to gh-pages are irrelevant
branches:
  only:
    - master