# Project information
site_name: 'Easy-Wi Webinterface'
site_description: 'A game and voice server and webspace webinterface'
site_author: 'Ulrich Block'
site_url: 'https://easy-wi.com'

# Address for local developement
dev_addr: '0.0.0.0:8080'

# Repository
repo_name: 'easy-wi/page'
repo_url: 'https://github.com/easy-wi/page'

# Copyright
copyright: 'Copyright &copy; 2017 Ulrich Block'

# Configuration
theme:
  custom_dir: theme/
  favicon: 'assets/img/favicon.ico'
  logo: 'assets/img/logo.png'
  feature:
    tabs: false
  name: 'material'
  language: 'en, de'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  search:
    language: 'en, de'
  social:
    - type: 'github'
      link: 'https://github.com/easy-wi/'
    - type: 'twitter'
      link: 'https://twitter.com/EasyWI/'
    - type: 'facebook'
      link: 'https://www.facebook.com/easywi/'
    - type: 'question-circle'
      link: 'https://gitter.im/easy-wi/'

# Extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Page tree
pages:
  - Easy-Wi: index.md
  - Downloads: downloads.md
  - Gallery: gallery.md
  - English:
    - News:
      - Easy-Wi Update 6.0.0: 'en/news/2017-05-14/easy-wi-update-6-0-0.md'
      - Easy-Wi Update 5.30: 'en/news/2016-05-08/easy-wi-update-5-30.md'
      - Easy-Wi Update 5.22: 'en/news/2016-03-25/easy-wi-update-5-22.md'
      - Installer Update 1.3: 'en/news/2016-02-27/installer-update-1-3.md'
      - Easy-Wi Update 5.21: 'en/news/2016-02-27/easy-wi-update-5-21.md'
      - Easy-Wi Update 5.2: 'en/news/2015-12-28/easy-wi-update-5-2.md'
      - Easy-Wi Update 5.1: 'en/news/2015-06-27/easy-wi-update-5-1.md'
      - Easy-Wi Update 5.0: 'en/news/2015-05-31/easy-wi-update-5-0.md'
      - Easy-Wi Update 4.4: 'en/news/2014-05-10/easy-wi-update-4-4.md'
      - Easy-Wi Update 4.3: 'en/news/2014-01-28/easy-wi-update-4-3.md'
      - Easy-Wi Update 4.2: 'en/news/2013-12-22/easy-wi-update-4-2.md'
      - Easy-Wi Update 4.11: 'en/news/2013-10-23/easy-wi-update-4-11.md'
      - Easy-Wi Update 4.10: 'en/news/2013-10-20/easy-wi-update-4-10.md'
      - Easy-Wi Update 4.0: 'en/news/2013-08-31/easy-wi-update-4-0.md'
#    - Installation:
#      - Web Interface: 'en/installation/web-interface.md'
#      - Game Root Server: 'en/installation/game-root-server.md'
#      - Voice Root Server: 'en/installation/voice-root-server.md'
#      - Image Server: 'en/installation/image-server.md'
  - Deutsch:
    - News:
      - Easy-Wi Update 6.0.0: 'de/news/2017-05-14/easy-wi-update-6-0-0.md'
      - Easy-Wi Update 5.30: 'de/news/2016-05-08/easy-wi-update-5-30.md'
      - Easy-Wi Update 5.22: 'de/news/2016-03-25/easy-wi-update-5-22.md'
      - Installer Update 1.3: 'de/news/2016-02-27/installer-update-1-3.md'
      - Easy-Wi Update 5.21: 'de/news/2016-02-27/easy-wi-update-5-21.md'
      - Easy-Wi Update 5.2: 'de/news/2015-12-28/easy-wi-update-5-2.md'
      - Easy-Wi Update 5.1: 'de/news/2015-06-27/easy-wi-update-5-1.md'
      - Easy-Wi Update 5.0: 'de/news/2015-05-31/easy-wi-update-5-0.md'
      - Easy-Wi Update 4.4: 'de/news/2014-05-10/easy-wi-update-4-4.md'
      - Easy-Wi Update 4.3: 'de/news/2014-01-28/easy-wi-update-4-3.md'
      - Easy-Wi Update 4.2: 'de/news/2013-12-22/easy-wi-update-4-2.md'
      - Easy-Wi Update 4.11: 'de/news/2013-10-23/easy-wi-update-4-11.md'
      - Easy-Wi Update 4.10: 'de/news/2013-10-20/easy-wi-update-4-10.md'
      - Easy-Wi Update 4.0: 'de/news/2013-08-31/easy-wi-update-4-0.md'
    - FAQ:
      - Anforderungen: 'de/faq/anforderungen.md'
      - Funktionen: 'de/faq/funktionen.md'
      - Game Server: 'de/faq/game-server.md'
    - Installation:
      - Web Interface: 'de/installation/web-interface.md'
      - Game Root Server: 'de/installation/game-root-server.md'
      - Image Server: 'de/installation/image-server.md'
      - Voice Root Server: 'de/installation/voice-root-server.md'
#      - Web Space: 'de/installation/web-space.md'
#      - MySQL Server: 'de/installation/mysql.md'
    - Admin:
#      - Home:
#        - Dashboard: 'de/admin/home/dashboard.md'
#        - IP Bans: 'de/admin/home/ip-bans.md'
#        - Logs: 'de/admin/home/logs.md'
#        - Mail Logs: 'de/admin/home/mail-logs.md'
#        - Impressum: 'de/admin/home/impressum.md'
#        - System Check: 'de/admin/home/system-check.md'
      - Einstellungen:
        - Einstellungen: 'de/admin/einstellungen/einstellungen.md'
        - E-Mail: 'de/admin/einstellungen/email.md'
        - Impressum: 'de/admin/einstellungen/imprint.md'
#          - Versionsüberprüfung: 'de/admin/einstellungen/versionsueberpruefung.md'
#          - Custom Columns: 'de/admin/einstellungen/custom-columns.md'
#          - Module: 'de/admin/einstellungen/module.md'
#          - DB: 'de/admin/einstellungen/db.md'
      - Jobs/API:
#          - Übersicht: 'de/admin/jobs-api/uebersicht.md'
        - API Einstellungen: 'de/admin/jobs-api/api-einstellungen.md'
        - Externe Authentifizierung: 'de/admin/jobs-api/externe-authentifizierung.md'
        - Benutzer Import: 'de/admin/jobs-api/benutzer-import.md'
#        - Feeds:
#          - News: 'de/admin/feeds/news.md'
#          - Übersicht: 'de/admin/feeds/uebersicht.md'
#          - Einstellungen: 'de/admin/feeds/einstellungen.md'
#        - CMS:
#          - News: 'de/admin/cms/news.md'
#          - Kommentare: 'de/admin/cms/kommentare.md'
#          - Seiten: 'de/admin/cms/seiten.md'
#          - Downloads: 'de/admin/cms/downloads.md'
#          - Einstellungen: 'de/admin/cms/einstellungen.md'
#        - Webspace:
#          - Übersicht: 'de/admin/webspace/uebersicht.md'
#          - Master: 'de/admin/webspace/master.md'
      - MySQL:
        - Übersicht: 'de/admin/mysql/uebersicht.md'
        - Master: 'de/admin/mysql/master.md'
#      - Benutzer:
#        - Übersicht: 'de/admin/benutzer/uebersicht.md'
#        - Gruppen: 'de/admin/benutzer/gruppen.md'
#        - Social Auth Provider: 'de/admin/benutzer/social-auth-provider.md'
      - Game Server:
#          - Übersicht: 'de/admin/game-server/uebersicht.md'
        - Templates: 'de/admin/game-server/templates.md'
        - Addons: 'de/admin/game-server/addons.md'
#          - Datei Templates : 'de/admin/game-server/datei-templates.md'
        - Easy Anti Cheat: 'de/admin/game-server/easy-anti-cheat.md'
      - App/Game Master:
        - Übersicht: 'de/admin/app-game-master/uebersicht.md'
        - Master Apps: 'de/admin/app-game-master/master-apps.md'
        - Master Apps Update: 'de/admin/app-game-master/apps-update.md'
#        - Voice Server:
#          - Übersicht: 'de/admin/voice-server/uebersicht.md'
#          - Master: 'de/admin/voice-server/master.md'
#          - TSDNS: 'de/admin/voice-server/tsdns-uebersicht.md'
#          - TSDNS Master: 'de/admin/voice-server/tsdns-master.md'
#          - Statistiken: 'de/admin/voice-server/statistiken.md'
      - Test/Lend Server:
        - Übersicht: 'de/admin/leih-server/uebersicht.md'
        - Einstellungen: 'de/admin/leih-server/einstelltungen.md'
#        - Support:
#          - Übersicht: 'de/admin/support/uebersicht.md'
#          - Einstellungen: 'de/admin/support/support-kategorien.md'
    - User:
      - Game Server:
        - Übersicht: 'de/user/game-server/uebersicht.md'
        - Fast Download: 'de/user/game-server/fast-download.md'
#          - Umzugsservice: 'de/user/game-server/umzugsservice.md'
#          - Datei Templates: 'de/user/game-server/datei-templates.md'
    - API:
      - Allgemeines: 'de/api/allgemeines.md'
      - Benutzer: 'de/api/benutzer.md'
      - Game Server: 'de/api/game-server.md'
      - Voice Server: 'de/api/voice-server.md'
      - MySQL: 'de/api/mysql.md'
      - Verleih Server: 'de/api/verleih-server.md'
      - Protectioncheck: 'de/api/protectioncheck.md'
      - Webspace: 'de/api/webspace.md'
  - License: license.md
  - Impressum/Imprint: impressum.md
  - Datenschutzerklärung: 'datenschutzerklaerung.md'